/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientContactDto } from '../../models/client-contact-dto';

export interface ClientContactControllerCreate$Params {
      body: ClientContactDto
}

export function clientContactControllerCreate(http: HttpClient, rootUrl: string, params: ClientContactControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ClientContactDto;
}>> {
  const rb = new RequestBuilder(rootUrl, clientContactControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: ClientContactDto;
      }>;
    })
  );
}

clientContactControllerCreate.PATH = '/nonauth/client_contact/client_contact';
