/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToolsWorkflowAggregatorDto } from '../../models/tools-workflow-aggregator-dto';

export interface WorkflowAggregatorControllerCreate$Params {
      body: ToolsWorkflowAggregatorDto
}

export function workflowAggregatorControllerCreate(http: HttpClient, rootUrl: string, params: WorkflowAggregatorControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowAggregatorDto;
}>> {
  const rb = new RequestBuilder(rootUrl, workflowAggregatorControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: ToolsWorkflowAggregatorDto;
      }>;
    })
  );
}

workflowAggregatorControllerCreate.PATH = '/auth/workflow_aggregator/workflow_aggregator';
