/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsMpartDto } from '../models/amims-mpart-dto';
export interface AmimsEngineerPmtrItemReportDto {
  createdAt?: string;
  figureIndex?: string;
  idEngineerPmtr?: string;
  idEngineerPmtrItem: string;
  idMpart?: string;
  mpart: AmimsMpartDto;
  noteItemPmtr?: string;
  priority?: string;
  qtyPmtr?: number;
  updatedAt?: string;
}
