/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsStoreTransferWidgetDto {
  createdAt?: string;
  dateReceived?: string;
  dateTransfer?: string;
  dimention?: string;
  idEngineerPmtr?: string;
  idStoreTransfer: string;
  idUserReceived?: string;
  idUserTransfer?: string;
  isDeleted?: number;
  noIndex?: number;
  noOfBox?: string;
  noteTransfer?: string;
  numberTransfer?: string;
  sheet?: string;
  shippingVia?: string;
  statusTransfer?: string;
  total?: number;
  updatedAt?: string;
  validasi?: number;
  weight?: string;
}
