/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsLibReferenceDto {
  createdAt?: string;
  idLibReference: string;
  lastUpdate?: string;
  nameFile?: string;
  numberReference?: string;
  updatedAt?: string;
}
