/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMaintenanceMaterialDto {
  createdAt?: string;
  idMaintenance?: string;
  idMaintenanceMaterial: string;
  idMpart?: string;
  isSpecialTool?: boolean;
  itemName?: string;
  itemType?: string;
  partNumber?: string;
  quantity?: number;
  status?: string;
  toolCode?: string;
  unit?: string;
  updatedAt?: string;
}
