/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsMaintenanceDto } from '../models/amims-maintenance-dto';
import { AmimsMpartDto } from '../models/amims-mpart-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
import { AmimsSiteDto } from '../models/amims-site-dto';
import { AmimsWpDto } from '../models/amims-wp-dto';
export interface AmimsWpJoReportDto {
  aircraft: AmimsAircraftDto;
  carriedOutDate?: string;
  completedAt?: string;
  compliteCycle?: number;
  compliteDate?: string;
  compliteHours?: number;
  createdAt?: string;
  cycleFrom?: number;
  cycleTo?: number;
  dateJo?: string;
  enginerApprovedBy?: string;
  enginerApprovedDate?: string;
  enginerApprovedNote?: number;
  formNo?: string;
  hourseFrom?: number;
  hourseTo?: number;
  idAircraft?: string;
  idDueListOutput?: string;
  idMaintenance?: string;
  idMaintenanceCode?: string;
  idMaintenanceProgram?: string;
  idMpart?: string;
  idPart?: string;
  idSite?: string;
  idTechLog?: string;
  idUnscheduleMaintenance?: string;
  idUser?: string;
  idWorkCompleted?: string;
  idWp?: string;
  idWpJo: string;
  inspectorApprovedAt?: string;
  inspectorApprovedBy?: string;
  inspectorApprovedNote?: string;
  maintenance: AmimsMaintenanceDto;
  mpart: AmimsMpartDto;
  noteJo?: string;
  numberJo?: string;
  parentEquipmentType?: string;
  part: AmimsPartDto;
  priority?: string;
  reference?: string;
  site: AmimsSiteDto;
  statusWpJo?: string;
  timeRangeFrom?: string;
  timeRangeTo?: number;
  timeVariable?: string;
  totalHoursWork?: number;
  typeOfwork?: string;
  updatedAt?: string;
  workDue?: string;
  wp: AmimsWpDto;
}
