/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsPartDto } from '../models/amims-part-dto';
export interface AmimsTechDiscrepanciesReportDto {
  createdAt?: string;
  dateDiscrepancies?: string;
  idPart?: string;
  idTechDiscrepancies: string;
  idTechLog?: string;
  isDiscrepancies?: string;
  noteDiscrepancies?: string;
  part: AmimsPartDto;
  updatedAt?: string;
}
