/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsMpartDto } from '../models/amims-mpart-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
export interface AmimsPurGrnItemReportDto {
  idMpart?: string;
  idPart?: string;
  idPurGrn?: string;
  idPurGrnItem: string;
  idPurPoItem?: string;
  mpart: AmimsMpartDto;
  noteGrnItem?: string;
  part: AmimsPartDto;
  qtyGrn?: number;
  serialNumber?: string;
  statusGrn?: string;
}
