/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsTechLogJoWidgetDto {
  createdAt?: string;
  dateClose?: string;
  idMpcJo?: string;
  idPart?: string;
  idTechLog?: string;
  idTechLogClose?: string;
  idTechLogJo: string;
  isContinue?: string;
  timeClose?: string;
  total?: number;
  updatedAt?: string;
}
