/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMaintenanceProgramTaskDto {
  createdAt?: string;
  idMaintenance?: string;
  idMaintenanceProgram: string;
  idMaintenanceProgramTask: string;
  noteTask?: string;
  urutan?: number;
}
