/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
export interface AmimsWorkCompletedReportDto {
  accountCode?: string;
  actualWorkHours?: number;
  adSbNumber?: string;
  adminNotes?: string;
  aircraft: AmimsAircraftDto;
  ataCode?: string;
  authority?: string;
  caseNumber?: string;
  completionDate: string;
  complianceDate?: string;
  complianceHours?: number;
  complianceLandings?: number;
  createdAt?: string;
  disposition?: string;
  engineerSign?: string;
  idAircraft: string;
  idPart?: string;
  idWorkCompleted: string;
  inspectorSign?: string;
  intervalDays?: number;
  intervalHours?: number;
  intervalLandings?: number;
  intervalMonths?: number;
  itemType?: string;
  location?: string;
  nextDueDate?: string;
  nextDueHours?: number;
  nextDueLandings?: number;
  part: AmimsPartDto;
  reference?: string;
  regularNotes?: string;
  releaseStatement?: string;
  remarks?: string;
  requirementType?: string;
  updatedAt?: string;
  workCompletedNumber: string;
  workSummary?: string;
}
