/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsWpJoDto {
  carriedOutDate?: string;
  completedAt?: string;
  compliteCycle?: number;
  compliteDate?: string;
  compliteHours?: number;
  createdAt?: string;
  cycleFrom?: number;
  cycleTo?: number;
  dateJo?: string;
  enginerApprovedBy?: string;
  enginerApprovedDate?: string;
  enginerApprovedNote?: number;
  formNo?: string;
  hourseFrom?: number;
  hourseTo?: number;
  idAircraft?: string;
  idDueListOutput?: string;
  idMaintenance?: string;
  idMaintenanceCode?: string;
  idMaintenanceProgram?: string;
  idMpart?: string;
  idPart?: string;
  idSite?: string;
  idTechLog?: string;
  idUnscheduleMaintenance?: string;
  idUser?: string;
  idWorkCompleted?: string;
  idWp?: string;
  idWpJo: string;
  inspectorApprovedAt?: string;
  inspectorApprovedBy?: string;
  inspectorApprovedNote?: string;
  noteJo?: string;
  numberJo?: string;
  parentEquipmentType?: string;
  priority?: string;
  reference?: string;
  statusWpJo?: string;
  timeRangeFrom?: string;
  timeRangeTo?: number;
  timeVariable?: string;
  totalHoursWork?: number;
  typeOfwork?: string;
  updatedAt?: string;
  workDue?: string;
}
