/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PelangganContractSiteDto {
  biayaAkhir?: number;
  biayaBulanan?: number;
  biayaDiawal?: number;
  catatan?: string;
  createdAt?: string;
  idClientSite: string;
  idContract: string;
  idContractSite: string;
  jumlahJadwalPerBulan?: number;
  statusContractSite?: string;
  updatedAt?: string;
}
