/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsRotaryFactorDto } from '../../models/amims-rotary-factor-dto';

export interface RotaryFactorControllerUpdate$Params {
  id: string;
      body: AmimsRotaryFactorDto
}

export function rotaryFactorControllerUpdate(http: HttpClient, rootUrl: string, params: RotaryFactorControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsRotaryFactorDto;
}>> {
  const rb = new RequestBuilder(rootUrl, rotaryFactorControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsRotaryFactorDto;
      }>;
    })
  );
}

rotaryFactorControllerUpdate.PATH = '/amims/rotary_factor/rotary_factor/{id}';
