/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsTechDefectDto } from '../../models/amims-tech-defect-dto';

export interface TechDefectControllerCreate$Params {
      body: AmimsTechDefectDto
}

export function techDefectControllerCreate(http: HttpClient, rootUrl: string, params: TechDefectControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechDefectDto;
}>> {
  const rb = new RequestBuilder(rootUrl, techDefectControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsTechDefectDto;
      }>;
    })
  );
}

techDefectControllerCreate.PATH = '/amims/tech_defect/tech_defect';
