/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsAtaDto } from '../models/amims-ata-dto';
import { AmimsMpartDto } from '../models/amims-mpart-dto';
export interface AmimsPartFigureIndexReportDto {
  ata: AmimsAtaDto;
  createdAt?: string;
  figureIndex?: string;
  idAta?: string;
  idMpart?: string;
  idPartFigureIndex: string;
  itemIndex?: string;
  mpart: AmimsMpartDto;
  updatedAt?: string;
}
