/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsEngineerPrisReturnReportDto {
  dateReturn?: string;
  idEngineerPris?: string;
  idEngineerPrisReturn: string;
  statusReturn?: string;
}
