/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMaintenanceDto {
  atachapter?: string;
  createdAt?: string;
  cycleFrom?: number;
  cycleTo?: number;
  flightHoursFrom?: number;
  flightHoursTo?: number;
  idMaintenance: string;
  idMaintenanceCode?: string;
  idMpart?: string;
  idUser?: string;
  noteMaintenance?: string;
  oldId?: string;
  onLocation?: string;
  repetitions?: number;
  timeRangeForm?: number;
  timeRangeTo?: number;
  timeUnit?: string;
  typeMaintenance?: string;
  updatedAt?: string;
}
