/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsPartInstallOldDto } from '../../models/amims-part-install-old-dto';

export interface PartInstallOldControllerFindOne$Params {
  id: string;
}

export function partInstallOldControllerFindOne(http: HttpClient, rootUrl: string, params: PartInstallOldControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartInstallOldDto;
}>> {
  const rb = new RequestBuilder(rootUrl, partInstallOldControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsPartInstallOldDto;
      }>;
    })
  );
}

partInstallOldControllerFindOne.PATH = '/amims/part_install_old/part_install_old/{id}';
