/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkScheduleDto } from '../../models/work-schedule-dto';

export interface WorkScheduleControllerRemove$Params {
  id: string;
}

export function workScheduleControllerRemove(http: HttpClient, rootUrl: string, params: WorkScheduleControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: WorkScheduleDto;
}>> {
  const rb = new RequestBuilder(rootUrl, workScheduleControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: WorkScheduleDto;
      }>;
    })
  );
}

workScheduleControllerRemove.PATH = '/nonauth/work_schedule/work_schedule/{id}';
