/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsInternalGrnReportDto } from '../../models/amims-internal-grn-report-dto';

export interface InternalGrnReportControllerFindOne$Params {
  id: string;
}

export function internalGrnReportControllerFindOne(http: HttpClient, rootUrl: string, params: InternalGrnReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsInternalGrnReportDto;
}>> {
  const rb = new RequestBuilder(rootUrl, internalGrnReportControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsInternalGrnReportDto;
      }>;
    })
  );
}

internalGrnReportControllerFindOne.PATH = '/amims/internal_grn/internal_grn_report/{id}';
