/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsTechLogJoDto } from '../../models/amims-tech-log-jo-dto';

export interface TechLogJoControllerFindOne$Params {
  id: string;
}

export function techLogJoControllerFindOne(http: HttpClient, rootUrl: string, params: TechLogJoControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogJoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, techLogJoControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsTechLogJoDto;
      }>;
    })
  );
}

techLogJoControllerFindOne.PATH = '/amims/tech_log_jo/tech_log_jo/{id}';
