/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AclUserGroupDto } from '../../models/acl-user-group-dto';

export interface UserGroupControllerCreate$Params {
      body: AclUserGroupDto
}

export function userGroupControllerCreate(http: HttpClient, rootUrl: string, params: UserGroupControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AclUserGroupDto;
}>> {
  const rb = new RequestBuilder(rootUrl, userGroupControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AclUserGroupDto;
      }>;
    })
  );
}

userGroupControllerCreate.PATH = '/auth/user_group/user_group';
