/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMlocationFlightDto } from '../../models/amims-mlocation-flight-dto';

export interface MlocationFlightControllerCreate$Params {
      body: AmimsMlocationFlightDto
}

export function mlocationFlightControllerCreate(http: HttpClient, rootUrl: string, params: MlocationFlightControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMlocationFlightDto;
}>> {
  const rb = new RequestBuilder(rootUrl, mlocationFlightControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMlocationFlightDto;
      }>;
    })
  );
}

mlocationFlightControllerCreate.PATH = '/amims/mlocation_flight/mlocation_flight';
