export const AmimsTechLogEngineReportDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "cycleBf": "number",
  "cycleCf": "number",
  "cycleFlight": "number",
  "fullCycleBf": "number",
  "fullCycleFlt": "number",
  "hoursBf": "number",
  "hoursCf": "number",
  "hoursFlight": "number",
  "idPart": "string",
  "idTechLog": "string",
  "idTechLogEngine": "string",
  "n1": "number",
  "n2": "number",
  "oil": "string",
  "oilAdd": "number",
  "oilTotal": "number",
  "oldId": "string",
  "part": "string",
  "partCycleBf": "number",
  "partCycleFlt": "number",
  "sn": "string",
  "timeAboveBf": "number",
  "timeAboveFlt": "number",
  "validasi": "number"
};
