import { AmimsCurrencyDto } from '../models/amims-currency-dto';
import { AmimsPositionDto } from '../models/amims-position-dto';
import { AmimsSiteDto } from '../models/amims-site-dto';
export interface AmimsPurPoReportDto {
    approveDirector?: number;
    createdAt?: string;
    currency: AmimsCurrencyDto;
    dateAcc?: string;
    dateAccDirector?: string;
    dateDeadline?: string;
    datePo?: string;
    idCurrency?: string;
    idPosition?: string;
    idPurPo: string;
    idPurVendor?: string;
    idPurVendorContact?: string;
    idSite?: string;
    idUser?: string;
    idUserDirector?: string;
    idUserManager?: string;
    isDeleted?: number;
    modeOfTransport?: string;
    noIndex?: number;
    notePo?: string;
    numberPo?: string;
    oldPo?: string;
    position: AmimsPositionDto;
    priceTotal?: number;
    quotationDate?: string;
    quotationNumber?: string;
    shipping?: string;
    site: AmimsSiteDto;
    statusPo?: string;
    term?: string;
    typePo?: string;
    updatedAt?: string;
    validasi?: number;
    vat?: number;
}
