import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
import { AmimsSiteDto } from '../models/amims-site-dto';
export interface AmimsEngineerRtiReportDto {
    aircraft: AmimsAircraftDto;
    base?: string;
    createdAt?: string;
    dateRti?: string;
    dispotition?: number;
    hasPris?: string;
    hashProcess?: string;
    hashRpd?: string;
    hashTechLog?: string;
    idAircraft?: string;
    idEngineerRti: string;
    idMpcJo?: string;
    idPart?: string;
    idPartInstall?: string;
    idSite?: string;
    inspectedBy?: number;
    numberRti?: string;
    part: AmimsPartDto;
    reason?: string;
    receivedBy?: number;
    remainingHours?: number;
    remarkDisposisi?: string;
    returnBy?: number;
    site: AmimsSiteDto;
    statusRti?: string;
    statusService?: string;
    tsnCycle?: number;
    tsnCycleParent?: number;
    tsnHours?: number;
    tsnHoursParent?: number;
    tsnVal?: number;
    tsnVar?: string;
    tsoCycle?: number;
    tsoHours?: number;
    tsoVal?: number;
    tsoVar?: string;
    typeRti?: string;
    updatedAt?: string;
}
