import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsPositionDto } from '../models/amims-position-dto';
import { AmimsSiteDto } from '../models/amims-site-dto';
export interface AmimsEngineerPrisReportDto {
    aircraft: AmimsAircraftDto;
    createdAt?: string;
    dateAcc?: string;
    dateClose?: string;
    dateInstall?: string;
    dateIssued?: string;
    datePris?: string;
    description?: string;
    idAircraft?: string;
    idEngineerPris: string;
    idPosition?: string;
    idSite?: string;
    idUser?: string;
    idUserAcc?: string;
    idUserClose?: string;
    idUserIssued?: string;
    isDeleted?: number;
    keyword?: string;
    noIndex?: number;
    notePris?: string;
    numberJo?: string;
    numberPris?: string;
    numberWp?: string;
    position: AmimsPositionDto;
    priority?: string;
    site: AmimsSiteDto;
    statusPris?: string;
    typePris?: string;
    updatedAt?: string;
    validasi?: number;
}
