import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
export interface AmimsTechLogReportDto {
    aircraft: AmimsAircraftDto;
    authoRized?: number;
    createdAt?: string;
    cycleBf?: number;
    cycleCf?: number;
    cycleFlight?: number;
    dateInspection?: string;
    hoursBf?: number;
    hoursCf?: number;
    hoursFlight?: number;
    idAircraft?: string;
    idTechLog: string;
    idUserAcc?: string;
    idUserInspection?: string;
    idUserLog?: string;
    isDeleted?: number;
    isEdit?: number;
    lastUpdate?: number;
    noteLog?: string;
    numberLog?: string;
    numberNext?: number;
    oldId?: string;
    pesan?: string;
    place?: number;
    techLogDate?: string;
    totalCycle?: number;
    totalFlight?: number;
    totalFuel?: number;
    updatedAt?: string;
    validasi?: number;
    xycleInput?: number;
}
