import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
export interface AmimsPartInstallOldReportDto {
    aircraft: AmimsAircraftDto;
    bin?: string;
    createdAt?: string;
    dateInstall?: string;
    dueOverhaulC?: number;
    dueOverhaulH?: number;
    dueOverhaulValue?: number;
    figureIndex?: string;
    idAircraft?: string;
    idEngineerPrisItem?: string;
    idPart?: string;
    idPartInstall?: string;
    idPartInstallOld: string;
    installedInspectionC?: number;
    installedInspectionH?: number;
    installedInspectionValue?: number;
    installedOverhaulC?: number;
    installedOverhaulH?: number;
    installedOverhaulValue?: number;
    isfeatured?: string;
    itemIndex?: string;
    oldId?: string;
    parent?: string;
    part: AmimsPartDto;
    qtyInstall?: number;
    statusInstall?: string;
    updatedAt?: string;
}
