/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsDueListWidgetDto } from '../models/amims-due-list-widget-dto';
import { dueListWidgetControllerFindAll } from '../fn/due-list-widget/due-list-widget-controller-find-all';
import { DueListWidgetControllerFindAll$Params } from '../fn/due-list-widget/due-list-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class DueListWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `dueListWidgetControllerFindAll()` */
  static readonly DueListWidgetControllerFindAllPath = '/amims/due_list/due_list_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dueListWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  dueListWidgetControllerFindAll$Response(params: DueListWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListWidgetDto>;
'total'?: number;
}>> {
    return dueListWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dueListWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  dueListWidgetControllerFindAll(params: DueListWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListWidgetDto>;
'total'?: number;
}> {
    return this.dueListWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
