/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPositionWidgetDto } from '../models/amims-position-widget-dto';
import { positionWidgetControllerFindAll } from '../fn/position-widget/position-widget-controller-find-all';
import { PositionWidgetControllerFindAll$Params } from '../fn/position-widget/position-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class PositionWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `positionWidgetControllerFindAll()` */
  static readonly PositionWidgetControllerFindAllPath = '/amims/position/position_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `positionWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  positionWidgetControllerFindAll$Response(params: PositionWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPositionWidgetDto>;
'total'?: number;
}>> {
    return positionWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `positionWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  positionWidgetControllerFindAll(params: PositionWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPositionWidgetDto>;
'total'?: number;
}> {
    return this.positionWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPositionWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPositionWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
