/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPurVendorReportDto } from '../models/amims-pur-vendor-report-dto';
import { purVendorReportControllerFindAll } from '../fn/pur-vendor-report/pur-vendor-report-controller-find-all';
import { PurVendorReportControllerFindAll$Params } from '../fn/pur-vendor-report/pur-vendor-report-controller-find-all';
import { purVendorReportControllerFindOne } from '../fn/pur-vendor-report/pur-vendor-report-controller-find-one';
import { PurVendorReportControllerFindOne$Params } from '../fn/pur-vendor-report/pur-vendor-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class PurVendorReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `purVendorReportControllerFindAll()` */
  static readonly PurVendorReportControllerFindAllPath = '/amims/pur_vendor/pur_vendor_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purVendorReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purVendorReportControllerFindAll$Response(params: PurVendorReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurVendorReportDto>;
'total'?: number;
}>> {
    return purVendorReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purVendorReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purVendorReportControllerFindAll(params: PurVendorReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurVendorReportDto>;
'total'?: number;
}> {
    return this.purVendorReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurVendorReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurVendorReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `purVendorReportControllerFindOne()` */
  static readonly PurVendorReportControllerFindOnePath = '/amims/pur_vendor/pur_vendor_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purVendorReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  purVendorReportControllerFindOne$Response(params: PurVendorReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurVendorReportDto;
}>> {
    return purVendorReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purVendorReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  purVendorReportControllerFindOne(params: PurVendorReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurVendorReportDto;
}> {
    return this.purVendorReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurVendorReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurVendorReportDto;
} => r.body)
    );
  }

}
