/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPurPrclWidgetDto } from '../models/amims-pur-prcl-widget-dto';
import { purPrclWidgetControllerFindAll } from '../fn/pur-prcl-widget/pur-prcl-widget-controller-find-all';
import { PurPrclWidgetControllerFindAll$Params } from '../fn/pur-prcl-widget/pur-prcl-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class PurPrclWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `purPrclWidgetControllerFindAll()` */
  static readonly PurPrclWidgetControllerFindAllPath = '/amims/pur_prcl/pur_prcl_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purPrclWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purPrclWidgetControllerFindAll$Response(params: PurPrclWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrclWidgetDto>;
'total'?: number;
}>> {
    return purPrclWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purPrclWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purPrclWidgetControllerFindAll(params: PurPrclWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrclWidgetDto>;
'total'?: number;
}> {
    return this.purPrclWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrclWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrclWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
