/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsTechLogEngineReportDto } from '../models/amims-tech-log-engine-report-dto';
import { techLogEngineReportControllerFindAll } from '../fn/tech-log-engine-report/tech-log-engine-report-controller-find-all';
import { TechLogEngineReportControllerFindAll$Params } from '../fn/tech-log-engine-report/tech-log-engine-report-controller-find-all';
import { techLogEngineReportControllerFindOne } from '../fn/tech-log-engine-report/tech-log-engine-report-controller-find-one';
import { TechLogEngineReportControllerFindOne$Params } from '../fn/tech-log-engine-report/tech-log-engine-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class TechLogEngineReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `techLogEngineReportControllerFindAll()` */
  static readonly TechLogEngineReportControllerFindAllPath = '/amims/tech_log_engine/tech_log_engine_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `techLogEngineReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  techLogEngineReportControllerFindAll$Response(params: TechLogEngineReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogEngineReportDto>;
'total'?: number;
}>> {
    return techLogEngineReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `techLogEngineReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  techLogEngineReportControllerFindAll(params: TechLogEngineReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogEngineReportDto>;
'total'?: number;
}> {
    return this.techLogEngineReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogEngineReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogEngineReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `techLogEngineReportControllerFindOne()` */
  static readonly TechLogEngineReportControllerFindOnePath = '/amims/tech_log_engine/tech_log_engine_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `techLogEngineReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  techLogEngineReportControllerFindOne$Response(params: TechLogEngineReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogEngineReportDto;
}>> {
    return techLogEngineReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `techLogEngineReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  techLogEngineReportControllerFindOne(params: TechLogEngineReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogEngineReportDto;
}> {
    return this.techLogEngineReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogEngineReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogEngineReportDto;
} => r.body)
    );
  }

}
