/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMpcWpDto } from '../../models/amims-mpc-wp-dto';

export interface MpcWpControllerUpdate$Params {
  id: string;
      body: AmimsMpcWpDto
}

export function mpcWpControllerUpdate(http: HttpClient, rootUrl: string, params: MpcWpControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMpcWpDto;
}>> {
  const rb = new RequestBuilder(rootUrl, mpcWpControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMpcWpDto;
      }>;
    })
  );
}

mpcWpControllerUpdate.PATH = '/amims/mpc_wp/mpc_wp/{id}';
