/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMaintenanceProgramTaskDto } from '../../models/amims-maintenance-program-task-dto';

export interface MaintenanceProgramTaskControllerFindOne$Params {
  id: string;
}

export function maintenanceProgramTaskControllerFindOne(http: HttpClient, rootUrl: string, params: MaintenanceProgramTaskControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramTaskDto;
}>> {
  const rb = new RequestBuilder(rootUrl, maintenanceProgramTaskControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMaintenanceProgramTaskDto;
      }>;
    })
  );
}

maintenanceProgramTaskControllerFindOne.PATH = '/amims/maintenance_program_task/maintenance_program_task/{id}';
