/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsPurReturnDto } from '../../models/amims-pur-return-dto';

export interface PurReturnControllerUpdate$Params {
  id: string;
      body: AmimsPurReturnDto
}

export function purReturnControllerUpdate(http: HttpClient, rootUrl: string, params: PurReturnControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurReturnDto;
}>> {
  const rb = new RequestBuilder(rootUrl, purReturnControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsPurReturnDto;
      }>;
    })
  );
}

purReturnControllerUpdate.PATH = '/amims/pur_return/pur_return/{id}';
