/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMpcSelfMaintenanceDto } from '../../models/amims-mpc-self-maintenance-dto';

export interface MpcSelfMaintenanceControllerFindOne$Params {
  id: string;
}

export function mpcSelfMaintenanceControllerFindOne(http: HttpClient, rootUrl: string, params: MpcSelfMaintenanceControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMpcSelfMaintenanceDto;
}>> {
  const rb = new RequestBuilder(rootUrl, mpcSelfMaintenanceControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMpcSelfMaintenanceDto;
      }>;
    })
  );
}

mpcSelfMaintenanceControllerFindOne.PATH = '/amims/mpc_self_maintenance/mpc_self_maintenance/{id}';
