export const AmimsDueListOutputDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "atInstall": "string",
  "ata": "string",
  "code": "string",
  "currentPart": "string",
  "dueAt": "string",
  "dueC": "number",
  "dueH": "number",
  "dueT": "number",
  "idAircraft": "string",
  "idDueList": "string",
  "idDueListOutput": "string",
  "idMaintenance": "string",
  "idMpart": "string",
  "idPart": "string",
  "installPart": "string",
  "keyword": "string",
  "noteDue": "string",
  "partNumber": "string",
  "peruntukan": "string",
  "ramaining": "number",
  "sn": "string",
  "toDue": "number",
  "typeDue": "string",
  "typeOfwork": "string",
  "variabel": "string"
};
