export const AmimsMaintenanceDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "alert": "number",
  "alertParam": "string",
  "atachapter": "string",
  "createdAt": "string",
  "cycleFrom": "number",
  "cycleTo": "number",
  "flightHoursFrom": "number",
  "flightHoursTo": "number",
  "idMaintenance": "string",
  "idMaintenanceCode": "string",
  "idMpart": "string",
  "idUser": "string",
  "noteMaintenance": "string",
  "oldId": "string",
  "onLocation": "string",
  "repetitions": "number",
  "timeRangeForm": "number",
  "timeRangeTo": "number",
  "timeUnit": "string",
  "typeMaintenance": "string",
  "updatedAt": "string"
};
