export const AmimsVDueListOutputWidgetDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "atInstallCy": "string",
  "atInstallDy": "string",
  "atInstallHr": "string",
  "ata": "string",
  "code": "string",
  "createdAt": "string",
  "dueAtCy": "string",
  "dueAtDy": "string",
  "dueAtHr": "string",
  "idDueListOutput": "string",
  "idMpart": "string",
  "idPart": "string",
  "keyword": "string",
  "lastPrice": "number",
  "lastPriceCurrency": "string",
  "noteDue": "string",
  "partNumber": "string",
  "partPrice": "number",
  "remainingCy": "number",
  "remainingDy": "number",
  "remainingHr": "number",
  "sn": "string",
  "toDueCy": "number",
  "toDueDy": "number",
  "toDueHr": "number",
  "total": "number"
};
