/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMaintenanceProgramMaterialDto } from '../../models/amims-maintenance-program-material-dto';

export interface MaintenanceProgramMaterialControllerRemove$Params {
  id: string;
}

export function maintenanceProgramMaterialControllerRemove(http: HttpClient, rootUrl: string, params: MaintenanceProgramMaterialControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramMaterialDto;
}>> {
  const rb = new RequestBuilder(rootUrl, maintenanceProgramMaterialControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMaintenanceProgramMaterialDto;
      }>;
    })
  );
}

maintenanceProgramMaterialControllerRemove.PATH = '/amims/maintenance_program_material/maintenance_program_material/{id}';
