/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsQaRpdDispotitionDto } from '../../models/amims-qa-rpd-dispotition-dto';

export interface QaRpdDispotitionControllerCreate$Params {
      body: AmimsQaRpdDispotitionDto
}

export function qaRpdDispotitionControllerCreate(http: HttpClient, rootUrl: string, params: QaRpdDispotitionControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsQaRpdDispotitionDto;
}>> {
  const rb = new RequestBuilder(rootUrl, qaRpdDispotitionControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsQaRpdDispotitionDto;
      }>;
    })
  );
}

qaRpdDispotitionControllerCreate.PATH = '/amims/qa_rpd_dispotition/qa_rpd_dispotition';
