/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsTdTypeDto } from '../../models/amims-td-type-dto';

export interface TdTypeControllerCreate$Params {
      body: AmimsTdTypeDto
}

export function tdTypeControllerCreate(http: HttpClient, rootUrl: string, params: TdTypeControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTdTypeDto;
}>> {
  const rb = new RequestBuilder(rootUrl, tdTypeControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsTdTypeDto;
      }>;
    })
  );
}

tdTypeControllerCreate.PATH = '/amims/td_type/td_type';
