/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsPartidWidgetDto {
  childnamePartid?: string;
  description?: string;
  idPartid: string;
  isDeleted?: number;
  issingle?: string;
  partid?: string;
  total?: number;
}
