/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsLastMaintenanceDto {
  createdAt?: string;
  idLastMaintenance: string;
  idMaintenance?: string;
  idMpcJo?: string;
  idPart?: string;
  idUser?: string;
  lastCycle?: number;
  lastDate?: string;
  lastHours?: number;
  oldId?: string;
  parentCycle?: number;
  parentHours?: number;
  typeOfWork?: number;
  updatedAt?: string;
}
