/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsShippingWidgetDto {
  createdAt?: string;
  idShipping: string;
  line0?: string;
  line1?: string;
  line2?: string;
  line3?: string;
  line4?: string;
  line5?: string;
  line6?: string;
  line7?: string;
  line8?: string;
  statusShipping?: string;
  total?: number;
  updatedAt?: string;
}
