/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMcurrencyDto {
  code?: string;
  createdAt?: string;
  currency?: string;
  idMcurrency: string;
  isDeleted?: number;
  statusCurrency?: string;
  updatedAt?: string;
  usdRate?: number;
}
