/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsPilotReportDto {
  createdAt?: string;
  hashIdUser?: number;
  idPilot: string;
  isDeleted?: number;
  namePilot?: string;
  status?: number;
  type?: string;
  updatedAt?: string;
}
