/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMaintenanceCodeReferenceDto {
  idLibReference?: string;
  idMaintenanceCode?: string;
  idMaintenanceCodeReference: string;
}
