/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsAtaWidgetDto } from '../../models/amims-ata-widget-dto';
import { BaseWidgetQueryDto } from '../../models/base-widget-query-dto';
import { Object } from '../../models/object';
import { SelectFieldDto } from '../../models/select-field-dto';

export interface AtaWidgetControllerFindAll$Params {

/**
 * Filter object
 */
  filter?: Object;

/**
 * JoinWhere object
 */
  joinWhere?: Object;

/**
 * Select fields with aggregation, e.g. [{ type: "sum", field: "nilai", alias: "totalNilai" }]
 */
  select?: Array<SelectFieldDto>;

/**
 * Fields to group by
 */
  groupBy?: Array<string>;
  sortKey?: string;
  sortValue?: 'ASC' | 'DESC';
      body: BaseWidgetQueryDto
}

export function ataWidgetControllerFindAll(http: HttpClient, rootUrl: string, params: AtaWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsAtaWidgetDto>;
'total'?: number;
}>> {
  const rb = new RequestBuilder(rootUrl, ataWidgetControllerFindAll.PATH, 'post');
  if (params) {
    rb.query('filter', params.filter, {});
    rb.query('joinWhere', params.joinWhere, {});
    rb.query('select', params.select, {});
    rb.query('groupBy', params.groupBy, {});
    rb.query('sortKey', params.sortKey, {});
    rb.query('sortValue', params.sortValue, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: Array<AmimsAtaWidgetDto>;
      'total'?: number;
      }>;
    })
  );
}

ataWidgetControllerFindAll.PATH = '/amims/ata/ata_widget';
