/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsTdDto {
  applicable?: string;
  createdAt?: string;
  docNumber?: string;
  effectiveDate?: string;
  fileTd?: string;
  idDoctype?: string;
  idTd: string;
  idUser?: string;
  noteDoc?: string;
  oldId?: string;
  rev?: string;
  tdParent?: string;
  title?: string;
  updatedAt?: string;
  validasi?: number;
}
