/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsCurrencyWidgetDto {
  createdAt?: string;
  effectiveDate?: string;
  forcurrency?: string;
  idCurrency: string;
  idMcurrency?: string;
  idUser?: string;
  newValue?: number;
  noteCurrency?: string;
  oldValue?: number;
  total?: number;
  updatedAt?: string;
}
