/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsLocationFlightWidgetDto {
  address?: string;
  createdAt?: string;
  idLocationFlight: string;
  lat?: string;
  lon?: string;
  nameLocation?: string;
  statusLocation?: string;
  total?: number;
  updatedAt?: string;
}
