/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsTechLogItemDto {
  apuStart?: number;
  cgPenalty?: string;
  cocaCaptain?: string;
  cycles?: number;
  flightFrom?: string;
  flightHours?: number;
  flightTo?: string;
  hoistOperation?: string;
  hoistUsage?: number;
  idCaptain?: string;
  idTechLog?: string;
  idTechLogItem: string;
  landingTime?: string;
  landings?: number;
  noteTechLogItem?: string;
  slingReleased?: number;
  takeofTime?: string;
}
