/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsEngineerPmtrWidgetDto {
  createdAt?: string;
  dateAcc?: string;
  datePmtr?: string;
  fromSite?: number;
  idAircraft?: string;
  idEngineerPmtr: string;
  idUser?: string;
  idUserAcc?: string;
  isDeleted?: number;
  noIndex?: number;
  notePmtr?: string;
  numberPmtr?: string;
  statusPmtr?: string;
  toSite?: number;
  total?: number;
  updatedAt?: string;
  validasi?: number;
}
