/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AmimsAircraftDto } from '../models/amims-aircraft-dto';
import { AmimsPartDto } from '../models/amims-part-dto';
export interface AmimsPartInstallReportDto {
  aircraft: AmimsAircraftDto;
  bin?: string;
  createdAt?: string;
  dateInstall?: string;
  dueOverhaulC?: number;
  dueOverhaulH?: number;
  dueOverhaulValue?: number;
  figureIndex?: string;
  idAircraft?: string;
  idEngineerPrisItem?: string;
  idPart?: string;
  idPartInstall: string;
  installedOverhaulC?: number;
  installedOverhaulH?: number;
  installedOverhaulValue?: number;
  installedParentC?: number;
  installedParentH?: number;
  installedParentValue?: number;
  installedTsnC?: number;
  installedTsnH?: number;
  isfeatured?: string;
  itemIndex?: string;
  newParen?: string;
  oldId?: string;
  oldIdPart?: string;
  oldParent?: string;
  onPris?: string;
  parent?: string;
  part: AmimsPartDto;
  qtyInstall?: number;
  refTechLog?: string;
  statusInstall?: string;
  topParent?: string;
  updatedAt?: string;
}
