/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsPartActypeWidgetDto {
  createdAt?: string;
  idActype?: string;
  idActypeOld?: string;
  idMpart?: string;
  idPartActype: string;
  total?: number;
  updatedAt?: string;
}
