/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AmimsMpcGseReportDto {
  createdAt?: string;
  dateGse?: string;
  idEngineerRti?: string;
  idMpcGse: string;
  idUserGse?: string;
  noteGse?: string;
  statusGse?: string;
  updatedAt?: string;
}
