/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AclUsers } from '../models/acl-users';
export interface AuthResponseDto {
  access_token: string;
  refresh_token: string;
  user: AclUsers;
}
