/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyConfigDto {
  alamat?: string;
  catatan?: string;
  createdAt?: string;
  idCompanyConfig: string;
  kontak?: string;
  logoUrl?: string;
  namaPerusahaan?: string;
  updatedAt?: string;
  versiErp?: string;
}
