/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactClientUseDto {
  catatan?: string;
  createdAt?: string;
  fromModule: string;
  fromModuleId: string;
  idClientContact: string;
  idContactClientUse: string;
  isPrimary?: boolean;
  peran?: string;
  updatedAt?: string;
}
