/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkScheduleTeknisiDto {
  catatan?: string;
  createdAt?: string;
  idSchedule: string;
  idScheduleTeknisi: string;
  idTeknisi: string;
  namaTeknisi: string;
  peran?: string;
}
