/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsEngineerRtiPartReportDto } from '../models/amims-engineer-rti-part-report-dto';
import { engineerRtiPartReportControllerFindAll } from '../fn/engineer-rti-part-report/engineer-rti-part-report-controller-find-all';
import { EngineerRtiPartReportControllerFindAll$Params } from '../fn/engineer-rti-part-report/engineer-rti-part-report-controller-find-all';
import { engineerRtiPartReportControllerFindOne } from '../fn/engineer-rti-part-report/engineer-rti-part-report-controller-find-one';
import { EngineerRtiPartReportControllerFindOne$Params } from '../fn/engineer-rti-part-report/engineer-rti-part-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class EngineerRtiPartReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `engineerRtiPartReportControllerFindAll()` */
  static readonly EngineerRtiPartReportControllerFindAllPath = '/amims/engineer_rti_part/engineer_rti_part_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `engineerRtiPartReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  engineerRtiPartReportControllerFindAll$Response(params: EngineerRtiPartReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiPartReportDto>;
'total'?: number;
}>> {
    return engineerRtiPartReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `engineerRtiPartReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  engineerRtiPartReportControllerFindAll(params: EngineerRtiPartReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiPartReportDto>;
'total'?: number;
}> {
    return this.engineerRtiPartReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiPartReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiPartReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `engineerRtiPartReportControllerFindOne()` */
  static readonly EngineerRtiPartReportControllerFindOnePath = '/amims/engineer_rti_part/engineer_rti_part_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `engineerRtiPartReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  engineerRtiPartReportControllerFindOne$Response(params: EngineerRtiPartReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiPartReportDto;
}>> {
    return engineerRtiPartReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `engineerRtiPartReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  engineerRtiPartReportControllerFindOne(params: EngineerRtiPartReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiPartReportDto;
}> {
    return this.engineerRtiPartReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiPartReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiPartReportDto;
} => r.body)
    );
  }

}
