/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsMaintenanceProgramReportDto } from '../models/amims-maintenance-program-report-dto';
import { maintenanceProgramReportControllerFindAll } from '../fn/maintenance-program-report/maintenance-program-report-controller-find-all';
import { MaintenanceProgramReportControllerFindAll$Params } from '../fn/maintenance-program-report/maintenance-program-report-controller-find-all';
import { maintenanceProgramReportControllerFindOne } from '../fn/maintenance-program-report/maintenance-program-report-controller-find-one';
import { MaintenanceProgramReportControllerFindOne$Params } from '../fn/maintenance-program-report/maintenance-program-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class MaintenanceProgramReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `maintenanceProgramReportControllerFindAll()` */
  static readonly MaintenanceProgramReportControllerFindAllPath = '/amims/maintenance_program/maintenance_program_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `maintenanceProgramReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  maintenanceProgramReportControllerFindAll$Response(params: MaintenanceProgramReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsMaintenanceProgramReportDto>;
'total'?: number;
}>> {
    return maintenanceProgramReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `maintenanceProgramReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  maintenanceProgramReportControllerFindAll(params: MaintenanceProgramReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsMaintenanceProgramReportDto>;
'total'?: number;
}> {
    return this.maintenanceProgramReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsMaintenanceProgramReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsMaintenanceProgramReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `maintenanceProgramReportControllerFindOne()` */
  static readonly MaintenanceProgramReportControllerFindOnePath = '/amims/maintenance_program/maintenance_program_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `maintenanceProgramReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  maintenanceProgramReportControllerFindOne$Response(params: MaintenanceProgramReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramReportDto;
}>> {
    return maintenanceProgramReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `maintenanceProgramReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  maintenanceProgramReportControllerFindOne(params: MaintenanceProgramReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramReportDto;
}> {
    return this.maintenanceProgramReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramReportDto;
} => r.body)
    );
  }

}
