/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ToolsWorkflowReportDto } from '../models/tools-workflow-report-dto';
import { workflowReportControllerFindAll } from '../fn/workflow-report/workflow-report-controller-find-all';
import { WorkflowReportControllerFindAll$Params } from '../fn/workflow-report/workflow-report-controller-find-all';
import { workflowReportControllerFindOne } from '../fn/workflow-report/workflow-report-controller-find-one';
import { WorkflowReportControllerFindOne$Params } from '../fn/workflow-report/workflow-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class WorkflowReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workflowReportControllerFindAll()` */
  static readonly WorkflowReportControllerFindAllPath = '/auth/workflow/workflow_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowReportControllerFindAll$Response(params: WorkflowReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowReportDto>;
'total'?: number;
}>> {
    return workflowReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowReportControllerFindAll(params: WorkflowReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowReportDto>;
'total'?: number;
}> {
    return this.workflowReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `workflowReportControllerFindOne()` */
  static readonly WorkflowReportControllerFindOnePath = '/auth/workflow/workflow_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowReportControllerFindOne$Response(params: WorkflowReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowReportDto;
}>> {
    return workflowReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowReportControllerFindOne(params: WorkflowReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowReportDto;
}> {
    return this.workflowReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowReportDto;
} => r.body)
    );
  }

}
