/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsWorkCompletedReportDto } from '../models/amims-work-completed-report-dto';
import { workCompletedReportControllerFindAll } from '../fn/work-completed-report/work-completed-report-controller-find-all';
import { WorkCompletedReportControllerFindAll$Params } from '../fn/work-completed-report/work-completed-report-controller-find-all';
import { workCompletedReportControllerFindOne } from '../fn/work-completed-report/work-completed-report-controller-find-one';
import { WorkCompletedReportControllerFindOne$Params } from '../fn/work-completed-report/work-completed-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class WorkCompletedReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workCompletedReportControllerFindAll()` */
  static readonly WorkCompletedReportControllerFindAllPath = '/amims/work_completed/work_completed_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workCompletedReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workCompletedReportControllerFindAll$Response(params: WorkCompletedReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWorkCompletedReportDto>;
'total'?: number;
}>> {
    return workCompletedReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workCompletedReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workCompletedReportControllerFindAll(params: WorkCompletedReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWorkCompletedReportDto>;
'total'?: number;
}> {
    return this.workCompletedReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWorkCompletedReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWorkCompletedReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `workCompletedReportControllerFindOne()` */
  static readonly WorkCompletedReportControllerFindOnePath = '/amims/work_completed/work_completed_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workCompletedReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  workCompletedReportControllerFindOne$Response(params: WorkCompletedReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWorkCompletedReportDto;
}>> {
    return workCompletedReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workCompletedReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workCompletedReportControllerFindOne(params: WorkCompletedReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWorkCompletedReportDto;
}> {
    return this.workCompletedReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWorkCompletedReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsWorkCompletedReportDto;
} => r.body)
    );
  }

}
