/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsWpJoReportDto } from '../models/amims-wp-jo-report-dto';
import { wpJoReportControllerFindAll } from '../fn/wp-jo-report/wp-jo-report-controller-find-all';
import { WpJoReportControllerFindAll$Params } from '../fn/wp-jo-report/wp-jo-report-controller-find-all';
import { wpJoReportControllerFindOne } from '../fn/wp-jo-report/wp-jo-report-controller-find-one';
import { WpJoReportControllerFindOne$Params } from '../fn/wp-jo-report/wp-jo-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class WpJoReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `wpJoReportControllerFindAll()` */
  static readonly WpJoReportControllerFindAllPath = '/amims/wp_jo/wp_jo_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `wpJoReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  wpJoReportControllerFindAll$Response(params: WpJoReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWpJoReportDto>;
'total'?: number;
}>> {
    return wpJoReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `wpJoReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  wpJoReportControllerFindAll(params: WpJoReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWpJoReportDto>;
'total'?: number;
}> {
    return this.wpJoReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWpJoReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsWpJoReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `wpJoReportControllerFindOne()` */
  static readonly WpJoReportControllerFindOnePath = '/amims/wp_jo/wp_jo_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `wpJoReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  wpJoReportControllerFindOne$Response(params: WpJoReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWpJoReportDto;
}>> {
    return wpJoReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `wpJoReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  wpJoReportControllerFindOne(params: WpJoReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWpJoReportDto;
}> {
    return this.wpJoReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsWpJoReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsWpJoReportDto;
} => r.body)
    );
  }

}
