export const AmimsRotaryFactorDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "adj1": "number",
  "adj2": "number",
  "adj3": "number",
  "dateCycle": "string",
  "dateHours": "string",
  "factor1": "number",
  "factor2": "number",
  "factor3": "number",
  "hoistLeft": "number",
  "hoistRight": "number",
  "idMpart": "string",
  "idRotaryFactor": "string",
  "noteHours": "string",
  "noteRotaryFactor": "string",
  "revisionCycle": "string",
  "revisionHours": "string",
  "rumusCycle": "string",
  "rumusHours": "string"
};
