export const AmimsEngineerRtiIdentifyWidgetDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "dateInstall": "string",
  "idEngineerRti": "string",
  "idEngineerRtiIdentify": "string",
  "idPart": "string",
  "idPartInstall": "string",
  "parent": "string",
  "total": "number",
  "tsiCycle": "number",
  "tsiHours": "number",
  "tsiVal": "number",
  "tsiVar": "string",
  "tsnCycle": "number",
  "tsnHours": "number",
  "tsnVal": "number",
  "tsnVar": "string",
  "tsoCycle": "number",
  "tsoHours": "number",
  "tsoVal": "number",
  "tsoVar": "string",
  "warantyStartCycle": "number",
  "warantyStartDate": "string",
  "warantyStartDays": "number",
  "warantyStartHours": "number"
};
