export const AmimsMpcPiroReportDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "aircraft": "string",
  "createdAt": "string",
  "dateAcc": "string",
  "datePiro": "string",
  "description": "string",
  "idAircraft": "string",
  "idMpcPiro": "string",
  "idSite": "string",
  "idUser": "string",
  "idUserAcc": "string",
  "isDeleted": "number",
  "keyword": "string",
  "noIndex": "number",
  "notePiro": "string",
  "numberPiro": "string",
  "site": "string",
  "statusPiro": "string",
  "typePiro": "string",
  "updatedAt": "string",
  "validasi": "number"
};
