export const PelangganClientWidgetDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "alamat": "string",
  "catatan": "string",
  "createdAt": "string",
  "emailPerusahaan": "string",
  "idClient": "string",
  "isAktif": "boolean",
  "jenisClient": "string",
  "kodeClient": "string",
  "kodePos": "string",
  "kota": "string",
  "logoUrl": "string",
  "namaFamiliar": "string",
  "namaResmi": "string",
  "npwp": "string",
  "primaryPic": "string",
  "provinsi": "string",
  "telepon": "string",
  "total": "number",
  "updatedAt": "string",
  "website": "string"
};
