/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsDueListOutputWidgetDto } from '../models/amims-due-list-output-widget-dto';
import { dueListOutputWidgetControllerFindAll } from '../fn/due-list-output-widget/due-list-output-widget-controller-find-all';
import { DueListOutputWidgetControllerFindAll$Params } from '../fn/due-list-output-widget/due-list-output-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class DueListOutputWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `dueListOutputWidgetControllerFindAll()` */
  static readonly DueListOutputWidgetControllerFindAllPath = '/amims/due_list_output/due_list_output_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dueListOutputWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  dueListOutputWidgetControllerFindAll$Response(params: DueListOutputWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListOutputWidgetDto>;
'total'?: number;
}>> {
    return dueListOutputWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dueListOutputWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  dueListOutputWidgetControllerFindAll(params: DueListOutputWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListOutputWidgetDto>;
'total'?: number;
}> {
    return this.dueListOutputWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListOutputWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsDueListOutputWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
