/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsEngineerRtiIdentifyReportDto } from '../models/amims-engineer-rti-identify-report-dto';
import { engineerRtiIdentifyReportControllerFindAll } from '../fn/engineer-rti-identify-report/engineer-rti-identify-report-controller-find-all';
import { EngineerRtiIdentifyReportControllerFindAll$Params } from '../fn/engineer-rti-identify-report/engineer-rti-identify-report-controller-find-all';
import { engineerRtiIdentifyReportControllerFindOne } from '../fn/engineer-rti-identify-report/engineer-rti-identify-report-controller-find-one';
import { EngineerRtiIdentifyReportControllerFindOne$Params } from '../fn/engineer-rti-identify-report/engineer-rti-identify-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class EngineerRtiIdentifyReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `engineerRtiIdentifyReportControllerFindAll()` */
  static readonly EngineerRtiIdentifyReportControllerFindAllPath = '/amims/engineer_rti_identify/engineer_rti_identify_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `engineerRtiIdentifyReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  engineerRtiIdentifyReportControllerFindAll$Response(params: EngineerRtiIdentifyReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiIdentifyReportDto>;
'total'?: number;
}>> {
    return engineerRtiIdentifyReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `engineerRtiIdentifyReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  engineerRtiIdentifyReportControllerFindAll(params: EngineerRtiIdentifyReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiIdentifyReportDto>;
'total'?: number;
}> {
    return this.engineerRtiIdentifyReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiIdentifyReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsEngineerRtiIdentifyReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `engineerRtiIdentifyReportControllerFindOne()` */
  static readonly EngineerRtiIdentifyReportControllerFindOnePath = '/amims/engineer_rti_identify/engineer_rti_identify_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `engineerRtiIdentifyReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  engineerRtiIdentifyReportControllerFindOne$Response(params: EngineerRtiIdentifyReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiIdentifyReportDto;
}>> {
    return engineerRtiIdentifyReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `engineerRtiIdentifyReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  engineerRtiIdentifyReportControllerFindOne(params: EngineerRtiIdentifyReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiIdentifyReportDto;
}> {
    return this.engineerRtiIdentifyReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiIdentifyReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiIdentifyReportDto;
} => r.body)
    );
  }

}
