/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsInternalGrnWidgetDto } from '../models/amims-internal-grn-widget-dto';
import { internalGrnWidgetControllerFindAll } from '../fn/internal-grn-widget/internal-grn-widget-controller-find-all';
import { InternalGrnWidgetControllerFindAll$Params } from '../fn/internal-grn-widget/internal-grn-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class InternalGrnWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `internalGrnWidgetControllerFindAll()` */
  static readonly InternalGrnWidgetControllerFindAllPath = '/amims/internal_grn/internal_grn_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `internalGrnWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internalGrnWidgetControllerFindAll$Response(params: InternalGrnWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsInternalGrnWidgetDto>;
'total'?: number;
}>> {
    return internalGrnWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `internalGrnWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  internalGrnWidgetControllerFindAll(params: InternalGrnWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsInternalGrnWidgetDto>;
'total'?: number;
}> {
    return this.internalGrnWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsInternalGrnWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsInternalGrnWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
