/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPartidReportDto } from '../models/amims-partid-report-dto';
import { partidReportControllerFindAll } from '../fn/partid-report/partid-report-controller-find-all';
import { PartidReportControllerFindAll$Params } from '../fn/partid-report/partid-report-controller-find-all';
import { partidReportControllerFindOne } from '../fn/partid-report/partid-report-controller-find-one';
import { PartidReportControllerFindOne$Params } from '../fn/partid-report/partid-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class PartidReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `partidReportControllerFindAll()` */
  static readonly PartidReportControllerFindAllPath = '/amims/partid/partid_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partidReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partidReportControllerFindAll$Response(params: PartidReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartidReportDto>;
'total'?: number;
}>> {
    return partidReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partidReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partidReportControllerFindAll(params: PartidReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartidReportDto>;
'total'?: number;
}> {
    return this.partidReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartidReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartidReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `partidReportControllerFindOne()` */
  static readonly PartidReportControllerFindOnePath = '/amims/partid/partid_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partidReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  partidReportControllerFindOne$Response(params: PartidReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartidReportDto;
}>> {
    return partidReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partidReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partidReportControllerFindOne(params: PartidReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartidReportDto;
}> {
    return this.partidReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartidReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartidReportDto;
} => r.body)
    );
  }

}
