/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPurGrnItemWidgetDto } from '../models/amims-pur-grn-item-widget-dto';
import { purGrnItemWidgetControllerFindAll } from '../fn/pur-grn-item-widget/pur-grn-item-widget-controller-find-all';
import { PurGrnItemWidgetControllerFindAll$Params } from '../fn/pur-grn-item-widget/pur-grn-item-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class PurGrnItemWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `purGrnItemWidgetControllerFindAll()` */
  static readonly PurGrnItemWidgetControllerFindAllPath = '/amims/pur_grn_item/pur_grn_item_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purGrnItemWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purGrnItemWidgetControllerFindAll$Response(params: PurGrnItemWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurGrnItemWidgetDto>;
'total'?: number;
}>> {
    return purGrnItemWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purGrnItemWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purGrnItemWidgetControllerFindAll(params: PurGrnItemWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurGrnItemWidgetDto>;
'total'?: number;
}> {
    return this.purGrnItemWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurGrnItemWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurGrnItemWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
