/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPurPrReportDto } from '../models/amims-pur-pr-report-dto';
import { purPrReportControllerFindAll } from '../fn/pur-pr-report/pur-pr-report-controller-find-all';
import { PurPrReportControllerFindAll$Params } from '../fn/pur-pr-report/pur-pr-report-controller-find-all';
import { purPrReportControllerFindOne } from '../fn/pur-pr-report/pur-pr-report-controller-find-one';
import { PurPrReportControllerFindOne$Params } from '../fn/pur-pr-report/pur-pr-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class PurPrReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `purPrReportControllerFindAll()` */
  static readonly PurPrReportControllerFindAllPath = '/amims/pur_pr/pur_pr_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purPrReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purPrReportControllerFindAll$Response(params: PurPrReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrReportDto>;
'total'?: number;
}>> {
    return purPrReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purPrReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  purPrReportControllerFindAll(params: PurPrReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrReportDto>;
'total'?: number;
}> {
    return this.purPrReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurPrReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `purPrReportControllerFindOne()` */
  static readonly PurPrReportControllerFindOnePath = '/amims/pur_pr/pur_pr_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `purPrReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  purPrReportControllerFindOne$Response(params: PurPrReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurPrReportDto;
}>> {
    return purPrReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `purPrReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  purPrReportControllerFindOne(params: PurPrReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurPrReportDto;
}> {
    return this.purPrReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurPrReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurPrReportDto;
} => r.body)
    );
  }

}
