/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsSiteWidgetDto } from '../models/amims-site-widget-dto';
import { siteWidgetControllerFindAll } from '../fn/site-widget/site-widget-controller-find-all';
import { SiteWidgetControllerFindAll$Params } from '../fn/site-widget/site-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class SiteWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `siteWidgetControllerFindAll()` */
  static readonly SiteWidgetControllerFindAllPath = '/amims/site/site_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `siteWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  siteWidgetControllerFindAll$Response(params: SiteWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsSiteWidgetDto>;
'total'?: number;
}>> {
    return siteWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `siteWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  siteWidgetControllerFindAll(params: SiteWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsSiteWidgetDto>;
'total'?: number;
}> {
    return this.siteWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsSiteWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsSiteWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
