/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsStockWidgetDto } from '../models/amims-stock-widget-dto';
import { stockWidgetControllerFindAll } from '../fn/stock-widget/stock-widget-controller-find-all';
import { StockWidgetControllerFindAll$Params } from '../fn/stock-widget/stock-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class StockWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `stockWidgetControllerFindAll()` */
  static readonly StockWidgetControllerFindAllPath = '/amims/stock/stock_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `stockWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  stockWidgetControllerFindAll$Response(params: StockWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsStockWidgetDto>;
'total'?: number;
}>> {
    return stockWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `stockWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  stockWidgetControllerFindAll(params: StockWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsStockWidgetDto>;
'total'?: number;
}> {
    return this.stockWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsStockWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsStockWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
