/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ToolsWorkflowLogReportDto } from '../models/tools-workflow-log-report-dto';
import { workflowLogReportControllerFindAll } from '../fn/workflow-log-report/workflow-log-report-controller-find-all';
import { WorkflowLogReportControllerFindAll$Params } from '../fn/workflow-log-report/workflow-log-report-controller-find-all';
import { workflowLogReportControllerFindOne } from '../fn/workflow-log-report/workflow-log-report-controller-find-one';
import { WorkflowLogReportControllerFindOne$Params } from '../fn/workflow-log-report/workflow-log-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class WorkflowLogReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workflowLogReportControllerFindAll()` */
  static readonly WorkflowLogReportControllerFindAllPath = '/auth/workflow_log/workflow_log_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowLogReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowLogReportControllerFindAll$Response(params: WorkflowLogReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowLogReportDto>;
'total'?: number;
}>> {
    return workflowLogReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowLogReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  workflowLogReportControllerFindAll(params: WorkflowLogReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowLogReportDto>;
'total'?: number;
}> {
    return this.workflowLogReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowLogReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<ToolsWorkflowLogReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `workflowLogReportControllerFindOne()` */
  static readonly WorkflowLogReportControllerFindOnePath = '/auth/workflow_log/workflow_log_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workflowLogReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowLogReportControllerFindOne$Response(params: WorkflowLogReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowLogReportDto;
}>> {
    return workflowLogReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workflowLogReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workflowLogReportControllerFindOne(params: WorkflowLogReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowLogReportDto;
}> {
    return this.workflowLogReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowLogReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowLogReportDto;
} => r.body)
    );
  }

}
