/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMaintenanceProgramDto } from '../../models/amims-maintenance-program-dto';

export interface MaintenanceProgramControllerUpdate$Params {
  id: string;
      body: AmimsMaintenanceProgramDto
}

export function maintenanceProgramControllerUpdate(http: HttpClient, rootUrl: string, params: MaintenanceProgramControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceProgramDto;
}>> {
  const rb = new RequestBuilder(rootUrl, maintenanceProgramControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMaintenanceProgramDto;
      }>;
    })
  );
}

maintenanceProgramControllerUpdate.PATH = '/amims/maintenance_program/maintenance_program/{id}';
