/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsEngineerRtiPartReportDto } from '../../models/amims-engineer-rti-part-report-dto';

export interface EngineerRtiPartReportControllerFindOne$Params {
  id: string;
}

export function engineerRtiPartReportControllerFindOne(http: HttpClient, rootUrl: string, params: EngineerRtiPartReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsEngineerRtiPartReportDto;
}>> {
  const rb = new RequestBuilder(rootUrl, engineerRtiPartReportControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsEngineerRtiPartReportDto;
      }>;
    })
  );
}

engineerRtiPartReportControllerFindOne.PATH = '/amims/engineer_rti_part/engineer_rti_part_report/{id}';
