/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsMaintenanceMaterialDto } from '../../models/amims-maintenance-material-dto';

export interface MaintenanceMaterialControllerUpdate$Params {
  id: string;
      body: AmimsMaintenanceMaterialDto
}

export function maintenanceMaterialControllerUpdate(http: HttpClient, rootUrl: string, params: MaintenanceMaterialControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsMaintenanceMaterialDto;
}>> {
  const rb = new RequestBuilder(rootUrl, maintenanceMaterialControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsMaintenanceMaterialDto;
      }>;
    })
  );
}

maintenanceMaterialControllerUpdate.PATH = '/amims/maintenance_material/maintenance_material/{id}';
