/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToolsCustomFieldGroupDto } from '../../models/tools-custom-field-group-dto';

export interface CustomFieldGroupControllerFindOne$Params {
  id: string;
}

export function customFieldGroupControllerFindOne(http: HttpClient, rootUrl: string, params: CustomFieldGroupControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsCustomFieldGroupDto;
}>> {
  const rb = new RequestBuilder(rootUrl, customFieldGroupControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: ToolsCustomFieldGroupDto;
      }>;
    })
  );
}

customFieldGroupControllerFindOne.PATH = '/auth/custom_field_group/custom_field_group/{id}';
