/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsPurVendorReportDto } from '../../models/amims-pur-vendor-report-dto';
import { BaseQueryDtoSmart } from '../../models/base-query-dto-smart';

export interface PurVendorReportControllerFindAll$Params {
      body: BaseQueryDtoSmart
}

export function purVendorReportControllerFindAll(http: HttpClient, rootUrl: string, params: PurVendorReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPurVendorReportDto>;
'total'?: number;
}>> {
  const rb = new RequestBuilder(rootUrl, purVendorReportControllerFindAll.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: Array<AmimsPurVendorReportDto>;
      'total'?: number;
      }>;
    })
  );
}

purVendorReportControllerFindAll.PATH = '/amims/pur_vendor/pur_vendor_report/list';
