/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsPurPrItemDto } from '../../models/amims-pur-pr-item-dto';

export interface PurPrItemControllerCreate$Params {
      body: AmimsPurPrItemDto
}

export function purPrItemControllerCreate(http: HttpClient, rootUrl: string, params: PurPrItemControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurPrItemDto;
}>> {
  const rb = new RequestBuilder(rootUrl, purPrItemControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsPurPrItemDto;
      }>;
    })
  );
}

purPrItemControllerCreate.PATH = '/amims/pur_pr_item/pur_pr_item';
