export const AmimsPurPrDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "createdAt": "string",
  "dateAcc": "string",
  "datePr": "string",
  "description": "string",
  "idAircraft": "string",
  "idPosition": "string",
  "idPurPr": "string",
  "idSite": "string",
  "idUser": "string",
  "idUserAcc": "string",
  "isDeleted": "number",
  "keyword": "string",
  "noIndex": "number",
  "notePr": "string",
  "numberPr": "string",
  "oldPr": "string",
  "statusPr": "string",
  "typePr": "string",
  "updatedAt": "string",
  "validasi": "number"
};
