export const AmimsTdDetailDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "applicable": "string",
  "createdAt": "string",
  "dateAcc": "string",
  "dateAccQa": "string",
  "dateDetail": "string",
  "fileDetail": "string",
  "idAcc": "string",
  "idAccQa": "string",
  "idActype": "string",
  "idTd": "string",
  "idTdDetail": "string",
  "isEngineer": "string",
  "isPilot": "string",
  "isQc": "string",
  "method": "string",
  "noteDetail": "string",
  "numberDetail": "string",
  "priority": "string",
  "statusTdDetail": "string",
  "subject": "string",
  "typeDetail": "string",
  "updatedAt": "string",
  "validasi": "number"
};
