export const AmimsActypeReportDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "acCategory": "string",
  "acManufacture": "string",
  "actype": "string",
  "createdAt": "string",
  "description": "string",
  "eFlight": "string",
  "eStarts": "string",
  "engineManufacture": "string",
  "engineType": "string",
  "hashN1": "string",
  "hashN2": "string",
  "idActype": "string",
  "isDeleted": "number",
  "numberEngine": "number",
  "oldId": "string",
  "statusType": "string",
  "updatedAt": "string",
  "wingtype": "string"
};
