export const AmimsSiteDtoFields: Record<string, 'string' | 'boolean' | 'number'> = {
  "address": "string",
  "city": "string",
  "codeSite": "string",
  "contactname": "string",
  "country": "string",
  "createdAt": "string",
  "emailaddress": "string",
  "fax": "string",
  "idNewSite": "string",
  "idSite": "string",
  "idUser": "string",
  "isDeleted": "number",
  "isMain": "number",
  "isStore": "string",
  "logoSite": "string",
  "mobile": "string",
  "oldId": "string",
  "parentSite": "number",
  "site": "string",
  "statusSite": "number",
  "telephone": "string",
  "typeSite": "string",
  "updatedAt": "string",
  "validation": "number"
};
