/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsPartConditionReportDto } from '../models/amims-part-condition-report-dto';
import { partConditionReportControllerFindAll } from '../fn/part-condition-report/part-condition-report-controller-find-all';
import { PartConditionReportControllerFindAll$Params } from '../fn/part-condition-report/part-condition-report-controller-find-all';
import { partConditionReportControllerFindOne } from '../fn/part-condition-report/part-condition-report-controller-find-one';
import { PartConditionReportControllerFindOne$Params } from '../fn/part-condition-report/part-condition-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class PartConditionReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `partConditionReportControllerFindAll()` */
  static readonly PartConditionReportControllerFindAllPath = '/amims/part_condition/part_condition_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partConditionReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partConditionReportControllerFindAll$Response(params: PartConditionReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartConditionReportDto>;
'total'?: number;
}>> {
    return partConditionReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partConditionReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  partConditionReportControllerFindAll(params: PartConditionReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartConditionReportDto>;
'total'?: number;
}> {
    return this.partConditionReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartConditionReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsPartConditionReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `partConditionReportControllerFindOne()` */
  static readonly PartConditionReportControllerFindOnePath = '/amims/part_condition/part_condition_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `partConditionReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  partConditionReportControllerFindOne$Response(params: PartConditionReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartConditionReportDto;
}>> {
    return partConditionReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `partConditionReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  partConditionReportControllerFindOne(params: PartConditionReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartConditionReportDto;
}> {
    return this.partConditionReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartConditionReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsPartConditionReportDto;
} => r.body)
    );
  }

}
