/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsQaTransferWidgetDto } from '../models/amims-qa-transfer-widget-dto';
import { qaTransferWidgetControllerFindAll } from '../fn/qa-transfer-widget/qa-transfer-widget-controller-find-all';
import { QaTransferWidgetControllerFindAll$Params } from '../fn/qa-transfer-widget/qa-transfer-widget-controller-find-all';

@Injectable({ providedIn: 'root' })
export class QaTransferWidgetService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `qaTransferWidgetControllerFindAll()` */
  static readonly QaTransferWidgetControllerFindAllPath = '/amims/qa_transfer/qa_transfer_widget';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `qaTransferWidgetControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  qaTransferWidgetControllerFindAll$Response(params: QaTransferWidgetControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsQaTransferWidgetDto>;
'total'?: number;
}>> {
    return qaTransferWidgetControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `qaTransferWidgetControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  qaTransferWidgetControllerFindAll(params: QaTransferWidgetControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsQaTransferWidgetDto>;
'total'?: number;
}> {
    return this.qaTransferWidgetControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsQaTransferWidgetDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsQaTransferWidgetDto>;
'total'?: number;
} => r.body)
    );
  }

}
