/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AmimsTechLogItemReportDto } from '../models/amims-tech-log-item-report-dto';
import { techLogItemReportControllerFindAll } from '../fn/tech-log-item-report/tech-log-item-report-controller-find-all';
import { TechLogItemReportControllerFindAll$Params } from '../fn/tech-log-item-report/tech-log-item-report-controller-find-all';
import { techLogItemReportControllerFindOne } from '../fn/tech-log-item-report/tech-log-item-report-controller-find-one';
import { TechLogItemReportControllerFindOne$Params } from '../fn/tech-log-item-report/tech-log-item-report-controller-find-one';

@Injectable({ providedIn: 'root' })
export class TechLogItemReportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `techLogItemReportControllerFindAll()` */
  static readonly TechLogItemReportControllerFindAllPath = '/amims/tech_log_item/tech_log_item_report/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `techLogItemReportControllerFindAll()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  techLogItemReportControllerFindAll$Response(params: TechLogItemReportControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogItemReportDto>;
'total'?: number;
}>> {
    return techLogItemReportControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `techLogItemReportControllerFindAll$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  techLogItemReportControllerFindAll(params: TechLogItemReportControllerFindAll$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogItemReportDto>;
'total'?: number;
}> {
    return this.techLogItemReportControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogItemReportDto>;
'total'?: number;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: Array<AmimsTechLogItemReportDto>;
'total'?: number;
} => r.body)
    );
  }

  /** Path part for operation `techLogItemReportControllerFindOne()` */
  static readonly TechLogItemReportControllerFindOnePath = '/amims/tech_log_item/tech_log_item_report/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `techLogItemReportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  techLogItemReportControllerFindOne$Response(params: TechLogItemReportControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogItemReportDto;
}>> {
    return techLogItemReportControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `techLogItemReportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  techLogItemReportControllerFindOne(params: TechLogItemReportControllerFindOne$Params, context?: HttpContext): Observable<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogItemReportDto;
}> {
    return this.techLogItemReportControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogItemReportDto;
}>): {
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogItemReportDto;
} => r.body)
    );
  }

}
