/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyConfigDto } from '../../models/company-config-dto';

export interface CompanyConfigControllerUpdate$Params {
  id: string;
      body: CompanyConfigDto
}

export function companyConfigControllerUpdate(http: HttpClient, rootUrl: string, params: CompanyConfigControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: CompanyConfigDto;
}>> {
  const rb = new RequestBuilder(rootUrl, companyConfigControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: CompanyConfigDto;
      }>;
    })
  );
}

companyConfigControllerUpdate.PATH = '/nonauth/company_config/company_config/{id}';
