/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PelangganContractSiteDto } from '../../models/pelanggan-contract-site-dto';

export interface ContractSiteControllerRemove$Params {
  id: string;
}

export function contractSiteControllerRemove(http: HttpClient, rootUrl: string, params: ContractSiteControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: PelangganContractSiteDto;
}>> {
  const rb = new RequestBuilder(rootUrl, contractSiteControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: PelangganContractSiteDto;
      }>;
    })
  );
}

contractSiteControllerRemove.PATH = '/auth/contract_site/contract_site/{id}';
