/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToolsWorkflowLogDto } from '../../models/tools-workflow-log-dto';

export interface WorkflowLogControllerRemove$Params {
  id: string;
}

export function workflowLogControllerRemove(http: HttpClient, rootUrl: string, params: WorkflowLogControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: ToolsWorkflowLogDto;
}>> {
  const rb = new RequestBuilder(rootUrl, workflowLogControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: ToolsWorkflowLogDto;
      }>;
    })
  );
}

workflowLogControllerRemove.PATH = '/auth/workflow_log/workflow_log/{id}';
