/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsTechLogEngineDto } from '../../models/amims-tech-log-engine-dto';

export interface TechLogEngineControllerRemove$Params {
  id: string;
}

export function techLogEngineControllerRemove(http: HttpClient, rootUrl: string, params: TechLogEngineControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsTechLogEngineDto;
}>> {
  const rb = new RequestBuilder(rootUrl, techLogEngineControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsTechLogEngineDto;
      }>;
    })
  );
}

techLogEngineControllerRemove.PATH = '/amims/tech_log_engine/tech_log_engine/{id}';
