/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmimsPurVendorContactDto } from '../../models/amims-pur-vendor-contact-dto';

export interface PurVendorContactControllerCreate$Params {
      body: AmimsPurVendorContactDto
}

export function purVendorContactControllerCreate(http: HttpClient, rootUrl: string, params: PurVendorContactControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'code'?: number;
'pesan'?: string;
'data'?: AmimsPurVendorContactDto;
}>> {
  const rb = new RequestBuilder(rootUrl, purVendorContactControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'code'?: number;
      'pesan'?: string;
      'data'?: AmimsPurVendorContactDto;
      }>;
    })
  );
}

purVendorContactControllerCreate.PATH = '/amims/pur_vendor_contact/pur_vendor_contact';
